import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogDescription,
	DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { X } from "lucide-react";

export function TermsOfServiceModal({ open, setOpen }) {
	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogContent className="max-w-3xl h-screen md:h-11/12">
				<button
					onClick={() => setOpen(false)}
					className="absolute right-4 top-4 rounded-md hover:opacity-80"
					type="button"
				>
					<X className="h-4 w-4" />
				</button>

				<DialogHeader>
					<DialogTitle>Terms of Service</DialogTitle>
					<DialogDescription>
						Please review the following terms carefully.
					</DialogDescription>
				</DialogHeader>

				<div className="h-full overflow-y-auto pr-2 space-y-4">
					<h2 className="text-lg font-semibold">🇬🇧 Terms of Service</h2>
					<p className="text-sm">
						<strong>Effective Date: April 1, 2025</strong>
						<br />
						Welcome to Chef! ("Service"). By using our Service, you agree to
						these Terms of Service ("Terms"). Please read them carefully.
					</p>

					<h3 className="font-semibold">1. Description of Service</h3>
					<p className="text-sm">
						Chef! provides AI-generated recipes using OpenAI's API. Recipes are
						automatically created based on your provided inputs, including
						ingredients, dietary preferences, and other relevant information.
					</p>

					<h3 className="font-semibold">2. Usage</h3>
					<p className="text-sm">
						You must use Chef! for lawful purposes only. You must not use the
						Service in any manner that infringes on the rights of others or
						violates applicable laws and regulations.
					</p>

					<h3 className="font-semibold">3. AI-Generated Content Disclaimer</h3>
					<p className="text-sm">
						All recipes generated by Chef! are created using artificial
						intelligence. We do not guarantee the accuracy, reliability, or
						suitability of generated recipes. Users should independently verify
						and ensure that recipes are safe, healthy, and suitable for their
						dietary needs.
					</p>

					<h3 className="font-semibold">
						4. Liability and Warranty Disclaimer
					</h3>
					<p className="text-sm">
						Chef! is provided "as is," without warranties of any kind. We are
						not responsible for any adverse outcomes resulting from using
						generated recipes, including but not limited to allergic reactions,
						food-related illness, or dissatisfaction with culinary outcomes.
					</p>

					<h3 className="font-semibold">5. User Responsibility</h3>
					<p className="text-sm">
						You are solely responsible for evaluating the safety,
						appropriateness, and effectiveness of recipes. Always review
						ingredients and methods thoroughly before preparation and
						consumption.
					</p>

					<h3 className="font-semibold">6. Intellectual Property</h3>
					<p className="text-sm">
						Recipes generated by Chef! may be used freely for personal and
						non-commercial purposes. Commercial use, including redistribution or
						resale of generated recipes without permission, is prohibited.
					</p>

					<h3 className="font-semibold">7. Changes to Terms</h3>
					<p className="text-sm">
						We reserve the right to modify these Terms at any time. Any updates
						will be communicated via Chef!. Continued use of the Service
						following changes indicates your acceptance of the revised Terms.
					</p>

					<h3 className="font-semibold">8. Termination</h3>
					<p className="text-sm">
						We may suspend or terminate your access to Chef! without notice if
						you violate these Terms or for other reasons at our discretion.
					</p>

					<h3 className="font-semibold">9. Governing Law</h3>
					<p className="text-sm">
						These Terms shall be governed by and construed in accordance with
						the laws applicable in your jurisdiction.
					</p>

					<h3 className="font-semibold">10. Contact Information</h3>
					<p className="text-sm">
						For questions regarding these Terms, please contact us at{" "}
						<a href="mailto:benjamin.vandamme@me.com">
							benjamin.vandamme@me.com
						</a>
						.
					</p>

					<p className="text-sm mt-2">
						By using Chef!, you acknowledge that you have read, understood, and
						agreed to these Terms of Service.
					</p>

					<hr className="my-6" />

					<h2 className="text-lg font-semibold">
						🇫🇷 Conditions Générales d'Utilisation
					</h2>
					<p className="text-sm">
						<strong>Date d'entrée en vigueur : 1er avril 2025</strong>
						<br />
						Bienvenue sur Chef! (« Service »). En utilisant notre Service, vous
						acceptez les présentes Conditions Générales d'Utilisation (« CGU »).
						Veuillez les lire attentivement.
					</p>

					<h3 className="font-semibold">1. Description du Service</h3>
					<p className="text-sm">
						Chef! propose des recettes générées par intelligence artificielle en
						utilisant l'API OpenAI. Les recettes sont automatiquement créées sur
						la base des informations que vous fournissez, notamment les
						ingrédients, les préférences alimentaires et autres informations
						pertinentes.
					</p>

					<h3 className="font-semibold">2. Utilisation</h3>
					<p className="text-sm">
						Vous devez utiliser Chef! uniquement à des fins légales. Vous ne
						devez pas utiliser le Service d'une manière qui viole les droits
						d'autrui ou qui enfreint les lois et réglementations applicables.
					</p>

					<h3 className="font-semibold">
						3. Clause de non-responsabilité concernant le contenu généré par IA
					</h3>
					<p className="text-sm">
						Toutes les recettes générées par Chef! sont créées grâce à
						l'intelligence artificielle. Nous ne garantissons pas l'exactitude,
						la fiabilité ou l'adéquation des recettes générées. Les utilisateurs
						doivent vérifier de manière indépendante que les recettes sont
						sûres, saines et adaptées à leurs besoins alimentaires.
					</p>

					<h3 className="font-semibold">
						4. Limitation de responsabilité et exclusion de garantie
					</h3>
					<p className="text-sm">
						Chef! est fourni « en l'état », sans garantie d'aucune sorte. Nous
						ne sommes pas responsables des conséquences négatives résultant de
						l'utilisation des recettes générées, y compris, mais sans s'y
						limiter, les réactions allergiques, maladies liées à l'alimentation
						ou insatisfaction quant au résultat culinaire.
					</p>

					<h3 className="font-semibold">5. Responsabilité de l'utilisateur</h3>
					<p className="text-sm">
						Vous êtes seul responsable d'évaluer la sécurité, la pertinence et
						l'efficacité des recettes. Vérifiez toujours attentivement les
						ingrédients et les méthodes avant la préparation et la consommation.
					</p>

					<h3 className="font-semibold">6. Propriété intellectuelle</h3>
					<p className="text-sm">
						Les recettes générées par Chef! peuvent être utilisées librement à
						des fins personnelles et non commerciales. L'utilisation
						commerciale, y compris la redistribution ou la revente des recettes
						générées sans autorisation, est interdite.
					</p>

					<h3 className="font-semibold">7. Modifications des Conditions</h3>
					<p className="text-sm">
						Nous nous réservons le droit de modifier ces CGU à tout moment.
						Toute mise à jour sera communiquée via Chef!. La poursuite de
						l'utilisation du Service après les modifications vaut acceptation
						des nouvelles CGU.
					</p>

					<h3 className="font-semibold">8. Résiliation</h3>
					<p className="text-sm">
						Nous pouvons suspendre ou résilier votre accès à Chef! sans préavis
						en cas de violation de ces CGU ou pour toute autre raison à notre
						discrétion.
					</p>

					<h3 className="font-semibold">9. Droit applicable</h3>
					<p className="text-sm">
						Ces CGU sont régies et interprétées conformément aux lois
						applicables dans votre juridiction.
					</p>

					<h3 className="font-semibold">10. Coordonnées de contact</h3>
					<p className="text-sm">
						Pour toute question concernant ces CGU, veuillez nous contacter à
						l'adresse suivante :{" "}
						<a href="mailto:benjamin.vandamme@me.com">
							benjamin.vandamme@me.com
						</a>
						.
					</p>

					<p className="text-sm mt-2">
						En utilisant Chef!, vous reconnaissez avoir lu, compris et accepté
						les présentes Conditions Générales d'Utilisation.
					</p>
				</div>

				<DialogFooter>
					<Button onClick={() => setOpen(false)}>OK</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}
