"""add relation between user and recipe

Revision ID: 0f7c4b24fe6a
Revises: f1bbeda853e3
Create Date: 2025-04-15 21:57:51.100832

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0f7c4b24fe6a'
down_revision = 'f1bbeda853e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    # ### end Alembic commands ###
