"""Auto migration

Revision ID: 21e02d1d6932
Revises: 0afde19f0981
Create Date: 2025-05-12 19:59:31.182129

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21e02d1d6932'
down_revision = '0afde19f0981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('number_of_accesses', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'number_of_accesses')
    # ### end Alembic commands ###
