"""Auto migration

Revision ID: 95e486204151
Revises: 21e02d1d6932
Create Date: 2025-05-12 20:23:20.738180

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '95e486204151'
down_revision = '21e02d1d6932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'deleted_at')
    # ### end Alembic commands ###
