"""Add column last_accessed_at to Recipe model

Revision ID: 9ff5d478d5ee
Revises: c84d52a00d66
Create Date: 2025-05-12 16:06:21.474981

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ff5d478d5ee'
down_revision = 'c84d52a00d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'last_accessed_at')
    # ### end Alembic commands ###
