"""add relation between user and recipe

Revision ID: f1bbeda853e3
Revises: 4582b6588d55
Create Date: 2025-04-15 21:49:23.923853

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f1bbeda853e3'
down_revision = '4582b6588d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('direction_recipe_id_fkey', 'direction', type_='foreignkey')
    op.create_foreign_key(None, 'direction', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ingredient_recipe_id_fkey', 'ingredient', type_='foreignkey')
    op.create_foreign_key(None, 'ingredient', 'recipe', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.create_foreign_key('ingredient_recipe_id_fkey', 'ingredient', 'recipe', ['recipe_id'], ['id'])
    op.drop_constraint(None, 'direction', type_='foreignkey')
    op.create_foreign_key('direction_recipe_id_fkey', 'direction', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
