export const promptExemples = {
  en: [
    "Suggest a quick recipe that takes less than 15 minutes to prepare.",
    "A delicious vegetarian recipe with seasonal vegetables and plant-based proteins.",
    "Easy and indulgent no-bake dessert with chocolate and red fruits.",
    "Healthy dinner recipe with grilled vegetables and a lean protein source.",
    "Homemade crepe batter recipe with tips for a light and fluffy texture.",
    "A refined dish to impress my guests, featuring seafood and a white wine sauce.",
    "A recipe with only 5 ingredients, balanced and flavorful.",
    "Energizing smoothie recipe with vitamin-rich fruits and a touch of protein.",
    "Creamy risotto recipe with parmesan and mushrooms for a melt-in-your-mouth texture.",
    "A special brunch dish, sweet or savory, based on eggs and simple pantry ingredients.",
    "Homemade pasta sauce recipe with fresh tomatoes, garlic, and aromatic herbs.",
    "Easy homemade curry with coconut milk, spices, and a vegetarian option.",
    "A recipe using leftover vegetables to reduce waste and create a tasty dish.",
    "Gourmet homemade burger with a juicy patty, melted cheese, and a unique sauce.",
    "Comforting winter soup made with pumpkin and warm spices.",
    "Refreshing non-alcoholic cocktail with citrus fruits and fresh herbs.",
    "Homemade lasagna recipe with slow-cooked Bolognese sauce and creamy béchamel.",
    "An easy and delicious gratin with melted cheese and a crispy texture.",
    "Molten chocolate cake recipe with a gooey center and minimal ingredients.",
    "Crustless quiche recipe, light and quick, perfect for an impromptu meal.",
    "A quick dish with canned tuna, pasta, and a creamy sauce.",
    "Homemade taco recipe with a flavorful filling and a spicy sauce.",
    "Easy and quick homemade pizza with an express dough and customizable toppings.",
    "Light wraps made with chicken, avocado, and yogurt sauce.",
    "Authentic carbonara pasta, without cream, with bacon and pecorino cheese.",
    "Spicy chili con carne slow-cooked with red beans and ground beef.",
    "A flavorful slow-cooked dish with tender meat and fragrant spices.",
    "Crispy homemade falafels made from chickpeas and fresh herbs.",
    "Fluffy homemade pancakes with a light, lump-free batter.",
    "Classic tiramisu recipe with creamy mascarpone and coffee-soaked biscuits.",
    "A stir-fry with crunchy vegetables, fragrant soy sauce, and sautéed tofu.",
    "No-bake cheesecake recipe with a crunchy biscuit base and fruity topping.",
    "Crispy homemade waffles with a well-risen and golden batter.",
    "Herb-roasted chicken recipe with perfect crispy skin.",
    "Refreshing summer salad with fruits, fresh cheese, and a tangy dressing.",
    "Creamy gratin dauphinois recipe with tender potatoes and melted cheese.",
    "Chocolate chip cookie recipe that's crispy on the outside and gooey inside.",
    "A salmon-based dish, rich in omega-3, with a light lemon sauce.",
    "Easy apple crumble recipe with a crispy shortbread topping and tender apples.",
    "Silky panna cotta recipe with a homemade red fruit coulis.",
    "Homemade bread recipe without a bread machine, with a golden crust and airy crumb.",
    "Ultra-fudgy brownies with a touch of sea salt and intense dark chocolate.",
    "Light strawberry tart with pastry cream and homemade shortcrust pastry.",
    "Stir-fried noodles recipe with homemade teriyaki sauce and crunchy vegetables.",
    "Traditional beef bourguignon slow-cooked with red wine and tender carrots.",
    "Breton-style buckwheat galettes with a complete and gourmet filling.",
    "Soft madeleine recipe with the perfect hump and a hint of lemon.",
    "A delicious vegan dish with marinated tofu and a creamy cashew sauce.",
    "Savoyard fondue recipe with a mix of melted cheeses and crispy bread.",
    "Light chocolate mousse recipe with only 3 ingredients and no cream.",
  ],
  fr: [
    "Proposez une recette rapide qui se prépare en moins de 15 minutes.",
    "Une délicieuse recette végétarienne avec des légumes de saison et des protéines végétales.",
    "Un dessert sans cuisson, facile et gourmand, à base de chocolat et de fruits rouges.",
    "Une recette de dîner équilibrée avec des légumes grillés et une source de protéines maigres.",
    "Une pâte à crêpes maison avec des conseils pour une texture légère et moelleuse.",
    "Un plat raffiné pour impressionner vos invités, à base de fruits de mer et d'une sauce au vin blanc.",
    "Une recette avec seulement 5 ingrédients, équilibrée et savoureuse.",
    "Un smoothie énergisant à base de fruits riches en vitamines et d'une touche de protéines.",
    "Un risotto crémeux au parmesan et aux champignons, pour une texture fondante.",
    "Un plat spécial brunch, sucré ou salé, à base d'œufs et d'ingrédients simples du garde-manger.",
    "Une sauce pour pâtes maison avec des tomates fraîches, de l'ail et des herbes aromatiques.",
    "Un curry maison facile avec du lait de coco, des épices et une option végétarienne.",
    "Une recette utilisant des légumes restants pour réduire le gaspillage et créer un plat savoureux.",
    "Un burger maison gourmet avec un steak juteux, du fromage fondu et une sauce unique.",
    "Une soupe hivernale réconfortante à base de potiron et d'épices chaudes.",
    "Un cocktail sans alcool rafraîchissant à base d'agrumes et d'herbes fraîches.",
    "Des lasagnes maison avec une sauce bolognaise mijotée et une béchamel onctueuse.",
    "Un gratin facile et délicieux avec du fromage fondu et une texture croustillante.",
    "Un fondant au chocolat avec un cœur coulant et peu d'ingrédients.",
    "Une quiche sans croûte, légère et rapide, parfaite pour un repas improvisé.",
    "Un plat rapide avec du thon en boîte, des pâtes et une sauce crémeuse.",
    "Des tacos maison avec une garniture savoureuse et une sauce épicée.",
    "Une pizza maison rapide et facile, avec une pâte express et des garnitures personnalisables.",
    "Des wraps légers au poulet, à l'avocat et à la sauce au yaourt.",
    "Des pâtes carbonara authentiques, sans crème, avec du bacon et du pecorino.",
    "Un chili con carne épicé, mijoté avec des haricots rouges et du bœuf haché.",
    "Un plat mijoté savoureux avec une viande tendre et des épices parfumées.",
    "Des falafels maison croustillants à base de pois chiches et d'herbes fraîches.",
    "Des pancakes maison moelleux avec une pâte légère et sans grumeaux.",
    "Un tiramisu classique avec un mascarpone onctueux et des biscuits imbibés de café.",
    "Un sauté de légumes croquants avec une sauce soja parfumée et du tofu poêlé.",
    "Un cheesecake sans cuisson, avec une base de biscuits croustillante et un coulis de fruits.",
    "Des gaufres maison croustillantes, avec une pâte bien levée et dorée.",
    "Un poulet rôti aux herbes avec une peau parfaitement croustillante.",
    "Une salade estivale rafraîchissante avec des fruits, du fromage frais et une vinaigrette acidulée.",
    "Un gratin dauphinois crémeux avec des pommes de terre fondantes et du fromage fondu.",
    "Une recette de cookies aux pépites de chocolat, croustillants à l'extérieur et moelleux à l'intérieur.",
    "Un plat à base de saumon, riche en oméga-3, avec une sauce légère au citron.",
    "Un crumble aux pommes facile avec une garniture sablée croustillante et des pommes fondantes.",
    "Une panna cotta onctueuse avec un coulis de fruits rouges maison.",
    "Un pain maison sans machine, avec une croûte dorée et une mie aérée.",
    "Des brownies ultra-fondants avec une pointe de sel de mer et du chocolat noir intense.",
    "Une tarte aux fraises légère, avec une crème pâtissière et une pâte sablée maison.",
    "Des nouilles sautées avec une sauce teriyaki maison et des légumes croquants.",
    "Un bœuf bourguignon traditionnel, mijoté avec du vin rouge et des carottes fondantes.",
    "Des galettes de sarrasin bretonnes avec une garniture complète et gourmande.",
    "Une recette de madeleines moelleuses avec la bosse parfaite et une touche de citron.",
    "Un délicieux plat végan avec du tofu mariné et une sauce crémeuse aux noix de cajou.",
    "Une fondue savoyarde avec un mélange de fromages fondus et du pain croustillant.",
    "Une mousse au chocolat légère, avec seulement 3 ingrédients et sans crème.",
  ],
};
