const promptExamples = [
  "Suggest a quick recipe that takes less than 15 minutes to prepare.",
  "A delicious vegetarian recipe with seasonal vegetables and plant-based proteins.",
  "Easy and indulgent no-bake dessert with chocolate and red fruits.",
  "Healthy dinner recipe with grilled vegetables and a lean protein source.",
  "Homemade crepe batter recipe with tips for a light and fluffy texture.",
  "A refined dish to impress my guests, featuring seafood and a white wine sauce.",
  "A recipe with only 5 ingredients, balanced and flavorful.",
  "Energizing smoothie recipe with vitamin-rich fruits and a touch of protein.",
  "Creamy risotto recipe with parmesan and mushrooms for a melt-in-your-mouth texture.",
  "A special brunch dish, sweet or savory, based on eggs and simple pantry ingredients.",
  "Homemade pasta sauce recipe with fresh tomatoes, garlic, and aromatic herbs.",
  "Easy homemade curry with coconut milk, spices, and a vegetarian option.",
  "A recipe using leftover vegetables to reduce waste and create a tasty dish.",
  "Gourmet homemade burger with a juicy patty, melted cheese, and a unique sauce.",
  "Comforting winter soup made with pumpkin and warm spices.",
  "Refreshing non-alcoholic cocktail with citrus fruits and fresh herbs.",
  "Homemade lasagna recipe with slow-cooked Bolognese sauce and creamy béchamel.",
  "An easy and delicious gratin with melted cheese and a crispy texture.",
  "Molten chocolate cake recipe with a gooey center and minimal ingredients.",
  "Crustless quiche recipe, light and quick, perfect for an impromptu meal.",
  "A quick dish with canned tuna, pasta, and a creamy sauce.",
  "Homemade taco recipe with a flavorful filling and a spicy sauce.",
  "Easy and quick homemade pizza with an express dough and customizable toppings.",
  "Light wraps made with chicken, avocado, and yogurt sauce.",
  "Authentic carbonara pasta, without cream, with bacon and pecorino cheese.",
  "Spicy chili con carne slow-cooked with red beans and ground beef.",
  "A flavorful slow-cooked dish with tender meat and fragrant spices.",
  "Crispy homemade falafels made from chickpeas and fresh herbs.",
  "Fluffy homemade pancakes with a light, lump-free batter.",
  "Classic tiramisu recipe with creamy mascarpone and coffee-soaked biscuits.",
  "A stir-fry with crunchy vegetables, fragrant soy sauce, and sautéed tofu.",
  "No-bake cheesecake recipe with a crunchy biscuit base and fruity topping.",
  "Crispy homemade waffles with a well-risen and golden batter.",
  "Herb-roasted chicken recipe with perfect crispy skin.",
  "Refreshing summer salad with fruits, fresh cheese, and a tangy dressing.",
  "Creamy gratin dauphinois recipe with tender potatoes and melted cheese.",
  "Chocolate chip cookie recipe that's crispy on the outside and gooey inside.",
  "A salmon-based dish, rich in omega-3, with a light lemon sauce.",
  "Easy apple crumble recipe with a crispy shortbread topping and tender apples.",
  "Silky panna cotta recipe with a homemade red fruit coulis.",
  "Homemade bread recipe without a bread machine, with a golden crust and airy crumb.",
  "Ultra-fudgy brownies with a touch of sea salt and intense dark chocolate.",
  "Light strawberry tart with pastry cream and homemade shortcrust pastry.",
  "Stir-fried noodles recipe with homemade teriyaki sauce and crunchy vegetables.",
  "Traditional beef bourguignon slow-cooked with red wine and tender carrots.",
  "Breton-style buckwheat galettes with a complete and gourmet filling.",
  "Soft madeleine recipe with the perfect hump and a hint of lemon.",
  "A delicious vegan dish with marinated tofu and a creamy cashew sauce.",
  "Savoyard fondue recipe with a mix of melted cheeses and crispy bread.",
  "Light chocolate mousse recipe with only 3 ingredients and no cream."
];

export default promptExamples;
